#!/bin/bash

MYXRANDR=/run/media/tnkpad/storage/Documents/custom_scripts

if xrandr | grep "eDP1 connected" && xrandr | grep "HDMI1 disconnected" && xrandr | grep "VGA1 disconnected"; then
	xrandr -s 0
	#xrandr --output eDP1 --primary --mode 1600x900_60.00 --rate 60.00
	$MYXRANDR/xrandr_set_primary

elif xrandr | grep "eDP1 connected" && xrandr | grep "HDMI1 connected" && xrandr | grep "VGA1 disconnected"; then
	#xrandr --output eDP1 --primary --mode 1600x900_60.00 --rate 60.00 --output HDMI1 --mode 3440x1440 --rate 50.00 --right-of eDP1
	$MYXRANDR/xrandr_set_1

elif xrandr | grep "eDP1 connected" && xrandr | grep "HDMI1 disconnected" && xrandr | grep "VGA1 connected"; then
	#xrandr --output eDP1 --primary --mode 1600x900_60.00 --rate 60.00 --output VGA1 --mode 1920x1080 --rate 60.00 --right-of eDP1
	$MYXRANDR/xrandr_set_2

elif xrandr | grep "eDP1 connected" && xrandr | grep "HDMI1 connected" && xrandr | grep "VGA1 connected"; then
	#xrandr --output eDP1 --primary --mode 1600x900_60.00 --rate 60.00 --output VGA1 --mode 1920x1080 --rate 60.00 --right-of eDP1 --output HDMI1 --mode 3440x1440 --rate 50.00 --right-of VGA1
	$MYXRANDR/xrandr_set_3

fi


